import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@/config";
import { Toaster } from "@/components/shadcn/ui/toaster";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const appConfig = config.appName;

export const metadata: Metadata = {
  title: appConfig,
  description: "Generated by Ooops",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${interFont.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
